services:
  app:
    build: .
    ports:
      - '3500:3500'
    environment:
      PORT: 3500
      DATABASE_URL: postgres://postgres:postgres@db:5432/campsim
    depends_on:
      - db
    command: sh -c "npm run db:push && node dist/server.js"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campsim
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
