version: '3.8'

services:
  app:
    build: .
    ports:
      - '3500:3500'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/campsim
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campsim
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
